2022-10-19 22:45:14,787  ###################################################### New MAIN run
2022-10-19 22:45:14,788  ##################### New run
2022-10-19 22:45:14,788  ##### Run updateGroupsMapping
2022-10-19 22:45:14,789  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:45:14,789  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-19 22:45:14,963  https://api.telegram.org:443 "POST /botTELEGRAM_TOKEN_TO_REPLACE/getUpdates HTTP/1.1" 404 55
2022-10-19 22:45:14,965  Error when getting Updates for bot: ('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})
2022-10-19 22:45:14,967  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 113, in updateGroupsMapping
    response = bot.getUpdates(offset=lastUpdateEvent)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 1000, in getUpdates
    return self._api_request('getUpdates', _rectify(p))
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})

2022-10-19 22:45:14,968  Groups: {'-530420856': {'messageInterval': 0.4, 'lastMessageTimestamp': 0}, '-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-19 22:45:14,969  ### Processing group: -530420856
2022-10-19 22:45:14,969  Time interval passed. Sending message
2022-10-19 22:45:14,970  Error when sending Telegram message: [Errno 2] No such file or directory: '/pig.jpg'
2022-10-19 22:45:14,970  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/pig.jpg'

2022-10-19 22:45:14,970  Error, message not sent.
2022-10-19 22:45:14,970  ### Processing group: -1001683374540
2022-10-19 22:45:14,971  Time interval passed. Sending message
2022-10-19 22:45:14,971  Error when sending Telegram message: [Errno 2] No such file or directory: '/pig.jpg'
2022-10-19 22:45:14,972  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/pig.jpg'

2022-10-19 22:45:14,972  Error, message not sent.
2022-10-19 22:45:14,973  Sleeping 30 seconds.
2022-10-19 22:45:45,000  ##################### New run
2022-10-19 22:45:45,001  ##### Run updateGroupsMapping
2022-10-19 22:45:45,004  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:45:45,059  https://api.telegram.org:443 "POST /botTELEGRAM_TOKEN_TO_REPLACE/getUpdates HTTP/1.1" 404 55
2022-10-19 22:45:45,061  Error when getting Updates for bot: ('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})
2022-10-19 22:45:45,062  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 113, in updateGroupsMapping
    response = bot.getUpdates(offset=lastUpdateEvent)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 1000, in getUpdates
    return self._api_request('getUpdates', _rectify(p))
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})

2022-10-19 22:45:45,064  Groups: {'-530420856': {'messageInterval': 0.4, 'lastMessageTimestamp': 0}, '-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-19 22:45:45,064  ### Processing group: -530420856
2022-10-19 22:45:45,064  Time interval passed. Sending message
2022-10-19 22:45:45,065  Error when sending Telegram message: [Errno 2] No such file or directory: 'pig.jpg'
2022-10-19 22:45:45,065  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'pig.jpg'

2022-10-19 22:45:45,066  Error, message not sent.
2022-10-19 22:45:45,066  ### Processing group: -1001683374540
2022-10-19 22:45:45,066  Time interval passed. Sending message
2022-10-19 22:45:45,067  Error when sending Telegram message: [Errno 2] No such file or directory: 'pig.jpg'
2022-10-19 22:45:45,067  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'pig.jpg'

2022-10-19 22:45:45,068  Error, message not sent.
2022-10-19 22:45:45,068  Sleeping 30 seconds.
2022-10-19 22:45:49,900  Quit
2022-10-19 22:45:51,443  ###################################################### New MAIN run
2022-10-19 22:45:51,444  ##################### New run
2022-10-19 22:45:51,444  ##### Run updateGroupsMapping
2022-10-19 22:45:51,447  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:45:51,447  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-19 22:45:51,610  https://api.telegram.org:443 "POST /botTELEGRAM_TOKEN_TO_REPLACE/getUpdates HTTP/1.1" 404 55
2022-10-19 22:45:51,612  Error when getting Updates for bot: ('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})
2022-10-19 22:45:51,614  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 113, in updateGroupsMapping
    response = bot.getUpdates(offset=lastUpdateEvent)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 1000, in getUpdates
    return self._api_request('getUpdates', _rectify(p))
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})

2022-10-19 22:45:51,615  Groups: {'-530420856': {'messageInterval': 0.4, 'lastMessageTimestamp': 0}, '-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-19 22:45:51,615  ### Processing group: -530420856
2022-10-19 22:45:51,615  Time interval passed. Sending message
2022-10-19 22:45:51,616  Error when sending Telegram message: [Errno 2] No such file or directory: 'pig.jpg'
2022-10-19 22:45:51,616  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'pig.jpg'

2022-10-19 22:45:51,616  Error, message not sent.
2022-10-19 22:45:51,617  ### Processing group: -1001683374540
2022-10-19 22:45:51,617  Time interval passed. Sending message
2022-10-19 22:45:51,617  Error when sending Telegram message: [Errno 2] No such file or directory: 'pig.jpg'
2022-10-19 22:45:51,617  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'pig.jpg'

2022-10-19 22:45:51,618  Error, message not sent.
2022-10-19 22:45:51,618  Sleeping 30 seconds.
2022-10-19 22:46:12,304  Quit
2022-10-19 22:46:41,256  ###################################################### New MAIN run
2022-10-19 22:46:41,257  ##################### New run
2022-10-19 22:46:41,257  ##### Run updateGroupsMapping
2022-10-19 22:46:41,259  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:46:41,260  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-19 22:46:41,429  https://api.telegram.org:443 "POST /botTELEGRAM_TOKEN_TO_REPLACE/getUpdates HTTP/1.1" 404 55
2022-10-19 22:46:41,430  Error when getting Updates for bot: ('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})
2022-10-19 22:46:41,432  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 113, in updateGroupsMapping
    response = bot.getUpdates(offset=lastUpdateEvent)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 1000, in getUpdates
    return self._api_request('getUpdates', _rectify(p))
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})

2022-10-19 22:46:41,433  Groups: {'-530420856': {'messageInterval': 0.4, 'lastMessageTimestamp': 0}, '-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-19 22:46:41,434  ### Processing group: -530420856
2022-10-19 22:46:41,434  Time interval passed. Sending message
2022-10-19 22:46:41,434  Error when sending Telegram message: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.jpg'
2022-10-19 22:46:41,435  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.jpg'

2022-10-19 22:46:41,435  Error, message not sent.
2022-10-19 22:46:41,435  ### Processing group: -1001683374540
2022-10-19 22:46:41,435  Time interval passed. Sending message
2022-10-19 22:46:41,436  Error when sending Telegram message: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.jpg'
2022-10-19 22:46:41,436  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.jpg'

2022-10-19 22:46:41,436  Error, message not sent.
2022-10-19 22:46:41,436  Sleeping 30 seconds.
2022-10-19 22:47:11,464  ##################### New run
2022-10-19 22:47:11,465  ##### Run updateGroupsMapping
2022-10-19 22:47:11,467  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:47:11,517  https://api.telegram.org:443 "POST /botTELEGRAM_TOKEN_TO_REPLACE/getUpdates HTTP/1.1" 404 55
2022-10-19 22:47:11,518  Error when getting Updates for bot: ('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})
2022-10-19 22:47:11,519  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 113, in updateGroupsMapping
    response = bot.getUpdates(offset=lastUpdateEvent)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 1000, in getUpdates
    return self._api_request('getUpdates', _rectify(p))
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})

2022-10-19 22:47:11,520  Groups: {'-530420856': {'messageInterval': 0.4, 'lastMessageTimestamp': 0}, '-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-19 22:47:11,520  ### Processing group: -530420856
2022-10-19 22:47:11,520  Time interval passed. Sending message
2022-10-19 22:47:11,520  Error when sending Telegram message: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.jpg'
2022-10-19 22:47:11,521  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.jpg'

2022-10-19 22:47:11,521  Error, message not sent.
2022-10-19 22:47:11,521  ### Processing group: -1001683374540
2022-10-19 22:47:11,521  Time interval passed. Sending message
2022-10-19 22:47:11,522  Error when sending Telegram message: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.jpg'
2022-10-19 22:47:11,522  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.jpg'

2022-10-19 22:47:11,522  Error, message not sent.
2022-10-19 22:47:11,523  Sleeping 30 seconds.
2022-10-19 22:47:41,554  ##################### New run
2022-10-19 22:47:41,557  ##### Run updateGroupsMapping
2022-10-19 22:47:41,561  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:47:41,612  https://api.telegram.org:443 "POST /botTELEGRAM_TOKEN_TO_REPLACE/getUpdates HTTP/1.1" 404 55
2022-10-19 22:47:41,613  Error when getting Updates for bot: ('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})
2022-10-19 22:47:41,613  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 113, in updateGroupsMapping
    response = bot.getUpdates(offset=lastUpdateEvent)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 1000, in getUpdates
    return self._api_request('getUpdates', _rectify(p))
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})

2022-10-19 22:47:41,615  Groups: {'-530420856': {'messageInterval': 0.4, 'lastMessageTimestamp': 0}, '-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-19 22:47:41,615  ### Processing group: -530420856
2022-10-19 22:47:41,615  Time interval passed. Sending message
2022-10-19 22:47:41,615  Error when sending Telegram message: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.jpg'
2022-10-19 22:47:41,616  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.jpg'

2022-10-19 22:47:41,616  Error, message not sent.
2022-10-19 22:47:41,616  ### Processing group: -1001683374540
2022-10-19 22:47:41,616  Time interval passed. Sending message
2022-10-19 22:47:41,617  Error when sending Telegram message: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.jpg'
2022-10-19 22:47:41,617  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.jpg'

2022-10-19 22:47:41,617  Error, message not sent.
2022-10-19 22:47:41,618  Sleeping 30 seconds.
2022-10-19 22:48:11,631  ##################### New run
2022-10-19 22:48:11,633  ##### Run updateGroupsMapping
2022-10-19 22:48:11,635  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:48:11,683  https://api.telegram.org:443 "POST /botTELEGRAM_TOKEN_TO_REPLACE/getUpdates HTTP/1.1" 404 55
2022-10-19 22:48:11,684  Error when getting Updates for bot: ('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})
2022-10-19 22:48:11,685  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 113, in updateGroupsMapping
    response = bot.getUpdates(offset=lastUpdateEvent)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 1000, in getUpdates
    return self._api_request('getUpdates', _rectify(p))
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})

2022-10-19 22:48:11,686  Groups: {'-530420856': {'messageInterval': 0.4, 'lastMessageTimestamp': 0}, '-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-19 22:48:11,686  ### Processing group: -530420856
2022-10-19 22:48:11,686  Time interval passed. Sending message
2022-10-19 22:48:11,687  Error when sending Telegram message: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.jpg'
2022-10-19 22:48:11,687  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.jpg'

2022-10-19 22:48:11,687  Error, message not sent.
2022-10-19 22:48:11,688  ### Processing group: -1001683374540
2022-10-19 22:48:11,688  Time interval passed. Sending message
2022-10-19 22:48:11,688  Error when sending Telegram message: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.jpg'
2022-10-19 22:48:11,688  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.jpg'

2022-10-19 22:48:11,689  Error, message not sent.
2022-10-19 22:48:11,689  Sleeping 30 seconds.
2022-10-19 22:48:41,707  ##################### New run
2022-10-19 22:48:41,709  ##### Run updateGroupsMapping
2022-10-19 22:48:41,711  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:48:41,761  https://api.telegram.org:443 "POST /botTELEGRAM_TOKEN_TO_REPLACE/getUpdates HTTP/1.1" 404 55
2022-10-19 22:48:41,762  Error when getting Updates for bot: ('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})
2022-10-19 22:48:41,763  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 113, in updateGroupsMapping
    response = bot.getUpdates(offset=lastUpdateEvent)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 1000, in getUpdates
    return self._api_request('getUpdates', _rectify(p))
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})

2022-10-19 22:48:41,764  Groups: {'-530420856': {'messageInterval': 0.4, 'lastMessageTimestamp': 0}, '-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-19 22:48:41,764  ### Processing group: -530420856
2022-10-19 22:48:41,764  Time interval passed. Sending message
2022-10-19 22:48:41,765  Error when sending Telegram message: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.jpg'
2022-10-19 22:48:41,765  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.jpg'

2022-10-19 22:48:41,765  Error, message not sent.
2022-10-19 22:48:41,765  ### Processing group: -1001683374540
2022-10-19 22:48:41,765  Time interval passed. Sending message
2022-10-19 22:48:41,766  Error when sending Telegram message: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.jpg'
2022-10-19 22:48:41,766  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.jpg'

2022-10-19 22:48:41,766  Error, message not sent.
2022-10-19 22:48:41,766  Sleeping 30 seconds.
2022-10-19 22:49:11,768  ##################### New run
2022-10-19 22:49:11,769  ##### Run updateGroupsMapping
2022-10-19 22:49:11,771  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:49:11,821  https://api.telegram.org:443 "POST /botTELEGRAM_TOKEN_TO_REPLACE/getUpdates HTTP/1.1" 404 55
2022-10-19 22:49:11,822  Error when getting Updates for bot: ('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})
2022-10-19 22:49:11,823  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 113, in updateGroupsMapping
    response = bot.getUpdates(offset=lastUpdateEvent)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 1000, in getUpdates
    return self._api_request('getUpdates', _rectify(p))
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})

2022-10-19 22:49:11,824  Groups: {'-530420856': {'messageInterval': 0.4, 'lastMessageTimestamp': 0}, '-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-19 22:49:11,824  ### Processing group: -530420856
2022-10-19 22:49:11,824  Time interval passed. Sending message
2022-10-19 22:49:11,825  Error when sending Telegram message: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.jpg'
2022-10-19 22:49:11,825  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.jpg'

2022-10-19 22:49:11,826  Error, message not sent.
2022-10-19 22:49:11,826  ### Processing group: -1001683374540
2022-10-19 22:49:11,826  Time interval passed. Sending message
2022-10-19 22:49:11,826  Error when sending Telegram message: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.jpg'
2022-10-19 22:49:11,827  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.jpg'

2022-10-19 22:49:11,827  Error, message not sent.
2022-10-19 22:49:11,827  Sleeping 30 seconds.
2022-10-19 22:49:40,339  Quit
2022-10-19 22:52:50,808  ###################################################### New MAIN run
2022-10-19 22:52:50,809  ##################### New run
2022-10-19 22:52:50,809  ##### Run updateGroupsMapping
2022-10-19 22:52:50,810  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:52:50,811  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-19 22:52:53,631  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 23
2022-10-19 22:52:53,632  No new updates for now. Nothing to add in the mappings file
2022-10-19 22:52:53,633  Groups: {'-530420856': {'messageInterval': 0.4, 'lastMessageTimestamp': 0}, '-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-19 22:52:53,633  ### Processing group: -530420856
2022-10-19 22:52:53,634  Time interval passed. Sending message
2022-10-19 22:52:53,634  Error when sending Telegram message: [Errno 2] No such file or directory: 'pig.jpg'
2022-10-19 22:52:53,636  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'pig.jpg'

2022-10-19 22:52:53,636  Error, message not sent.
2022-10-19 22:52:53,636  ### Processing group: -1001683374540
2022-10-19 22:52:53,637  Time interval passed. Sending message
2022-10-19 22:52:53,637  Error when sending Telegram message: [Errno 2] No such file or directory: 'pig.jpg'
2022-10-19 22:52:53,638  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'pig.jpg'

2022-10-19 22:52:53,638  Error, message not sent.
2022-10-19 22:52:53,638  Sleeping 30 seconds.
2022-10-19 22:53:23,656  ##################### New run
2022-10-19 22:53:23,657  ##### Run updateGroupsMapping
2022-10-19 22:53:23,660  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:53:23,721  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 23
2022-10-19 22:53:23,722  No new updates for now. Nothing to add in the mappings file
2022-10-19 22:53:23,722  Groups: {'-530420856': {'messageInterval': 0.4, 'lastMessageTimestamp': 0}, '-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-19 22:53:23,722  ### Processing group: -530420856
2022-10-19 22:53:23,723  Time interval passed. Sending message
2022-10-19 22:53:23,723  Error when sending Telegram message: [Errno 2] No such file or directory: 'pig.jpg'
2022-10-19 22:53:23,723  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'pig.jpg'

2022-10-19 22:53:23,724  Error, message not sent.
2022-10-19 22:53:23,724  ### Processing group: -1001683374540
2022-10-19 22:53:23,724  Time interval passed. Sending message
2022-10-19 22:53:23,725  Error when sending Telegram message: [Errno 2] No such file or directory: 'pig.jpg'
2022-10-19 22:53:23,725  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'pig.jpg'

2022-10-19 22:53:23,725  Error, message not sent.
2022-10-19 22:53:23,725  Sleeping 30 seconds.
2022-10-19 22:53:27,035  Quit
2022-10-19 22:53:28,269  ###################################################### New MAIN run
2022-10-19 22:53:28,270  ##################### New run
2022-10-19 22:53:28,270  ##### Run updateGroupsMapping
2022-10-19 22:53:28,271  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:53:28,272  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-19 22:53:28,465  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 23
2022-10-19 22:53:28,466  No new updates for now. Nothing to add in the mappings file
2022-10-19 22:53:28,466  Groups: {'-530420856': {'messageInterval': 0.4, 'lastMessageTimestamp': 0}, '-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-19 22:53:28,467  ### Processing group: -530420856
2022-10-19 22:53:28,467  Time interval passed. Sending message
2022-10-19 22:53:28,468  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:53:28,576  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendMessage HTTP/1.1" 400 73
2022-10-19 22:53:28,578  Error when sending Telegram message: ('Bad Request: chat not found', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: chat not found'})
2022-10-19 22:53:28,581  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 59, in sendTelegramMessage
    bot.sendMessage(chatId, message)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 513, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Request: chat not found', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: chat not found'})

2022-10-19 22:53:28,583  Error, message not sent.
2022-10-19 22:53:28,583  ### Processing group: -1001683374540
2022-10-19 22:53:28,583  Time interval passed. Sending message
2022-10-19 22:53:28,584  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:53:28,680  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendMessage HTTP/1.1" 400 73
2022-10-19 22:53:28,681  Error when sending Telegram message: ('Bad Request: chat not found', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: chat not found'})
2022-10-19 22:53:28,682  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 59, in sendTelegramMessage
    bot.sendMessage(chatId, message)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 513, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Request: chat not found', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: chat not found'})

2022-10-19 22:53:28,684  Error, message not sent.
2022-10-19 22:53:28,685  Sleeping 30 seconds.
2022-10-19 22:53:58,712  ##################### New run
2022-10-19 22:53:58,713  ##### Run updateGroupsMapping
2022-10-19 22:53:58,715  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:53:58,769  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 23
2022-10-19 22:53:58,770  No new updates for now. Nothing to add in the mappings file
2022-10-19 22:53:58,770  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-19 22:53:58,771  ### Processing group: -1001683374540
2022-10-19 22:53:58,771  Time interval passed. Sending message
2022-10-19 22:53:58,772  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:53:58,868  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendMessage HTTP/1.1" 400 73
2022-10-19 22:53:58,869  Error when sending Telegram message: ('Bad Request: chat not found', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: chat not found'})
2022-10-19 22:53:58,870  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 59, in sendTelegramMessage
    bot.sendMessage(chatId, message)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 513, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Request: chat not found', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: chat not found'})

2022-10-19 22:53:58,872  Error, message not sent.
2022-10-19 22:53:58,872  Sleeping 30 seconds.
2022-10-19 22:54:28,888  ##################### New run
2022-10-19 22:54:28,889  ##### Run updateGroupsMapping
2022-10-19 22:54:28,891  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:54:28,950  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-19 22:54:28,952  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-19 22:54:28,952  ### Processing group: -1001683374540
2022-10-19 22:54:28,952  Time interval passed. Sending message
2022-10-19 22:54:28,953  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:54:29,017  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendMessage HTTP/1.1" 400 73
2022-10-19 22:54:29,018  Error when sending Telegram message: ('Bad Request: chat not found', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: chat not found'})
2022-10-19 22:54:29,019  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 59, in sendTelegramMessage
    bot.sendMessage(chatId, message)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 513, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Request: chat not found', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: chat not found'})

2022-10-19 22:54:29,020  Error, message not sent.
2022-10-19 22:54:29,020  Sleeping 30 seconds.
2022-10-19 22:54:59,030  ##################### New run
2022-10-19 22:54:59,031  ##### Run updateGroupsMapping
2022-10-19 22:54:59,033  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:54:59,094  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 2074
2022-10-19 22:54:59,095  Bot was added to group: Хорошие новости - новости ИТшника with chat id: -1001683374540
2022-10-19 22:54:59,096  This is a new group, add it to the group mapping file
2022-10-19 22:54:59,096  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-19 22:54:59,097  ### Processing group: -1001683374540
2022-10-19 22:54:59,097  Time interval passed. Sending message
2022-10-19 22:54:59,098  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:54:59,209  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendMessage HTTP/1.1" 200 437
2022-10-19 22:54:59,210  Message successfully sent.
2022-10-19 22:54:59,210  Sleeping 30 seconds.
2022-10-19 22:55:29,212  ##################### New run
2022-10-19 22:55:29,213  ##### Run updateGroupsMapping
2022-10-19 22:55:29,215  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:55:29,271  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-19 22:55:29,272  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666209299.0974846}}
2022-10-19 22:55:29,273  ### Processing group: -1001683374540
2022-10-19 22:55:29,273  Time interval not already passed. Wait 149.82427883148193 seconds.
2022-10-19 22:55:29,273  Sleeping 30 seconds.
2022-10-19 22:55:59,304  ##################### New run
2022-10-19 22:55:59,305  ##### Run updateGroupsMapping
2022-10-19 22:55:59,307  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:55:59,372  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-19 22:55:59,373  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666209299.0974846}}
2022-10-19 22:55:59,373  ### Processing group: -1001683374540
2022-10-19 22:55:59,374  Time interval not already passed. Wait 119.72343826293945 seconds.
2022-10-19 22:55:59,374  Sleeping 30 seconds.
2022-10-19 22:56:29,376  ##################### New run
2022-10-19 22:56:29,377  ##### Run updateGroupsMapping
2022-10-19 22:56:29,379  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:56:29,432  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-19 22:56:29,434  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666209299.0974846}}
2022-10-19 22:56:29,434  ### Processing group: -1001683374540
2022-10-19 22:56:29,434  Time interval not already passed. Wait 89.66297554969788 seconds.
2022-10-19 22:56:29,434  Sleeping 30 seconds.
2022-10-19 22:56:59,464  ##################### New run
2022-10-19 22:56:59,466  ##### Run updateGroupsMapping
2022-10-19 22:56:59,468  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:56:59,524  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-19 22:56:59,525  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666209299.0974846}}
2022-10-19 22:56:59,525  ### Processing group: -1001683374540
2022-10-19 22:56:59,525  Time interval not already passed. Wait 59.57170605659485 seconds.
2022-10-19 22:56:59,526  Sleeping 30 seconds.
2022-10-19 22:57:29,536  ##################### New run
2022-10-19 22:57:29,537  ##### Run updateGroupsMapping
2022-10-19 22:57:29,540  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:57:29,592  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-19 22:57:29,593  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666209299.0974846}}
2022-10-19 22:57:29,594  ### Processing group: -1001683374540
2022-10-19 22:57:29,594  Time interval not already passed. Wait 29.502835988998413 seconds.
2022-10-19 22:57:29,595  Sleeping 30 seconds.
2022-10-19 22:57:59,596  ##################### New run
2022-10-19 22:57:59,597  ##### Run updateGroupsMapping
2022-10-19 22:57:59,599  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:57:59,652  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-19 22:57:59,654  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666209299.0974846}}
2022-10-19 22:57:59,654  ### Processing group: -1001683374540
2022-10-19 22:57:59,654  Time interval passed. Sending message
2022-10-19 22:57:59,655  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:57:59,789  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendMessage HTTP/1.1" 200 437
2022-10-19 22:57:59,789  Message successfully sent.
2022-10-19 22:57:59,790  Sleeping 30 seconds.
2022-10-19 22:58:29,821  ##################### New run
2022-10-19 22:58:29,823  ##### Run updateGroupsMapping
2022-10-19 22:58:29,828  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:58:29,882  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-19 22:58:29,883  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666209479.6544163}}
2022-10-19 22:58:29,883  ### Processing group: -1001683374540
2022-10-19 22:58:29,884  Time interval not already passed. Wait 149.77029371261597 seconds.
2022-10-19 22:58:29,884  Sleeping 30 seconds.
2022-10-19 22:58:59,907  ##################### New run
2022-10-19 22:58:59,908  ##### Run updateGroupsMapping
2022-10-19 22:58:59,909  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:58:59,963  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-19 22:58:59,964  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666209479.6544163}}
2022-10-19 22:58:59,964  ### Processing group: -1001683374540
2022-10-19 22:58:59,964  Time interval not already passed. Wait 119.68966388702393 seconds.
2022-10-19 22:58:59,965  Sleeping 30 seconds.
2022-10-19 22:59:29,980  ##################### New run
2022-10-19 22:59:29,982  ##### Run updateGroupsMapping
2022-10-19 22:59:29,984  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 22:59:30,038  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-19 22:59:30,040  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666209479.6544163}}
2022-10-19 22:59:30,040  ### Processing group: -1001683374540
2022-10-19 22:59:30,040  Time interval not already passed. Wait 89.61345505714417 seconds.
2022-10-19 22:59:30,041  Sleeping 30 seconds.
2022-10-19 23:00:00,069  ##################### New run
2022-10-19 23:00:00,070  ##### Run updateGroupsMapping
2022-10-19 23:00:00,072  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 23:00:00,132  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-19 23:00:00,134  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666209479.6544163}}
2022-10-19 23:00:00,134  ### Processing group: -1001683374540
2022-10-19 23:00:00,134  Time interval not already passed. Wait 59.519803285598755 seconds.
2022-10-19 23:00:00,134  Sleeping 30 seconds.
2022-10-19 23:00:24,600  Quit
2022-10-19 23:04:07,998  ###################################################### New MAIN run
2022-10-19 23:04:08,000  ##################### New run
2022-10-19 23:04:08,000  ##### Run updateGroupsMapping
2022-10-19 23:04:08,001  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 23:04:08,002  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-19 23:04:08,172  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-19 23:04:08,173  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-19 23:04:08,174  ### Processing group: -1001683374540
2022-10-19 23:04:08,174  Time interval passed. Sending message
2022-10-19 23:04:08,175  Error when sending Telegram message: [Errno 20] Not a directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/picturePath.txt/pig.png'
2022-10-19 23:04:08,175  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/telegramBotSendMessageToGroups.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
NotADirectoryError: [Errno 20] Not a directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/picturePath.txt/pig.png'

2022-10-19 23:04:08,176  Error, message not sent.
2022-10-19 23:04:08,176  Sleeping 30 seconds.
2022-10-19 23:04:24,692  Quit
2022-10-19 23:04:57,792  ###################################################### New MAIN run
2022-10-19 23:04:57,792  ##################### New run
2022-10-19 23:04:57,792  ##### Run updateGroupsMapping
2022-10-19 23:04:57,794  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 23:04:57,794  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-19 23:04:57,956  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-19 23:04:57,958  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-19 23:04:57,959  ### Processing group: -1001683374540
2022-10-19 23:04:57,959  Time interval passed. Sending message
2022-10-19 23:04:57,971  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 23:04:57,972  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-19 23:04:58,298  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 811
2022-10-19 23:04:58,299  Message successfully sent.
2022-10-19 23:04:58,299  Sleeping 30 seconds.
2022-10-19 23:05:26,321  Quit
2022-10-19 23:05:41,995  ###################################################### New MAIN run
2022-10-19 23:05:41,996  ##################### New run
2022-10-19 23:05:41,996  ##### Run updateGroupsMapping
2022-10-19 23:05:41,998  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 23:05:41,999  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-19 23:05:42,182  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-19 23:05:42,184  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-19 23:05:42,184  ### Processing group: -1001683374540
2022-10-19 23:05:42,185  Time interval passed. Sending message
2022-10-19 23:05:42,195  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 23:05:42,196  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-19 23:05:42,589  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 815
2022-10-19 23:05:42,593  Message successfully sent.
2022-10-19 23:05:42,593  Sleeping 30 seconds.
2022-10-19 23:06:12,624  ##################### New run
2022-10-19 23:06:12,627  ##### Run updateGroupsMapping
2022-10-19 23:06:12,629  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 23:06:12,693  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-19 23:06:12,698  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666209942.1852605}}
2022-10-19 23:06:12,700  ### Processing group: -1001683374540
2022-10-19 23:06:12,701  Time interval not already passed. Wait 149.48404145240784 seconds.
2022-10-19 23:06:12,701  Sleeping 30 seconds.
2022-10-19 23:06:42,732  ##################### New run
2022-10-19 23:06:42,735  ##### Run updateGroupsMapping
2022-10-19 23:06:42,738  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 23:06:42,797  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-19 23:06:42,799  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666209942.1852605}}
2022-10-19 23:06:42,800  ### Processing group: -1001683374540
2022-10-19 23:06:42,800  Time interval not already passed. Wait 119.3849561214447 seconds.
2022-10-19 23:06:42,800  Sleeping 30 seconds.
2022-10-19 23:07:00,641  Quit
2022-10-19 23:07:01,985  ###################################################### New MAIN run
2022-10-19 23:07:01,986  ##################### New run
2022-10-19 23:07:01,987  ##### Run updateGroupsMapping
2022-10-19 23:07:01,990  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 23:07:01,990  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-19 23:07:02,157  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-19 23:07:02,159  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-19 23:07:02,160  ### Processing group: -1001683374540
2022-10-19 23:07:02,160  Time interval passed. Sending message
2022-10-19 23:07:02,169  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 23:07:02,170  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-19 23:07:02,496  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 811
2022-10-19 23:07:02,497  Message successfully sent.
2022-10-19 23:07:02,498  Sleeping 1800 seconds.
2022-10-19 23:37:02,581  ##################### New run
2022-10-19 23:37:02,584  ##### Run updateGroupsMapping
2022-10-19 23:37:02,588  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 23:37:02,589  Resetting dropped connection: api.telegram.org
2022-10-19 23:37:02,757  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-19 23:37:02,758  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666210022.1606026}}
2022-10-19 23:37:02,758  ### Processing group: -1001683374540
2022-10-19 23:37:02,758  Time interval passed. Sending message
2022-10-19 23:37:02,760  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-19 23:37:02,760  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-19 23:37:03,055  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 811
2022-10-19 23:37:03,056  Message successfully sent.
2022-10-19 23:37:03,056  Sleeping 1800 seconds.
2022-10-20 00:07:03,128  ##################### New run
2022-10-20 00:07:03,131  ##### Run updateGroupsMapping
2022-10-20 00:07:03,134  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 00:07:03,135  Resetting dropped connection: api.telegram.org
2022-10-20 00:07:03,311  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 00:07:03,312  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666211822.7588725}}
2022-10-20 00:07:03,312  ### Processing group: -1001683374540
2022-10-20 00:07:03,312  Time interval passed. Sending message
2022-10-20 00:07:03,313  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 00:07:03,314  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 00:07:03,562  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 811
2022-10-20 00:07:03,563  Message successfully sent.
2022-10-20 00:07:03,563  Sleeping 1800 seconds.
2022-10-20 00:37:03,584  ##################### New run
2022-10-20 00:37:03,587  ##### Run updateGroupsMapping
2022-10-20 00:37:03,590  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 00:37:03,591  Resetting dropped connection: api.telegram.org
2022-10-20 00:37:03,744  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 00:37:03,745  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666213623.312698}}
2022-10-20 00:37:03,745  ### Processing group: -1001683374540
2022-10-20 00:37:03,745  Time interval passed. Sending message
2022-10-20 00:37:03,747  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 00:37:03,747  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 00:37:04,057  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 815
2022-10-20 00:37:04,058  Message successfully sent.
2022-10-20 00:37:04,058  Sleeping 1800 seconds.
2022-10-20 01:07:04,088  ##################### New run
2022-10-20 01:07:04,090  ##### Run updateGroupsMapping
2022-10-20 01:07:04,092  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 01:07:04,093  Resetting dropped connection: api.telegram.org
2022-10-20 01:07:04,275  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 01:07:04,277  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666215423.745793}}
2022-10-20 01:07:04,277  ### Processing group: -1001683374540
2022-10-20 01:07:04,277  Time interval passed. Sending message
2022-10-20 01:07:04,279  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 01:07:04,279  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 01:07:04,537  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 811
2022-10-20 01:07:04,538  Message successfully sent.
2022-10-20 01:07:04,538  Sleeping 1800 seconds.
2022-10-20 01:37:04,608  ##################### New run
2022-10-20 01:37:04,611  ##### Run updateGroupsMapping
2022-10-20 01:37:04,613  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 01:37:04,613  Resetting dropped connection: api.telegram.org
2022-10-20 01:37:04,794  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 01:37:04,795  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666217224.2778964}}
2022-10-20 01:37:04,796  ### Processing group: -1001683374540
2022-10-20 01:37:04,796  Time interval passed. Sending message
2022-10-20 01:37:04,797  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 01:37:04,797  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 01:37:05,063  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 811
2022-10-20 01:37:05,064  Message successfully sent.
2022-10-20 01:37:05,064  Sleeping 1800 seconds.
2022-10-20 02:07:05,132  ##################### New run
2022-10-20 02:07:05,135  ##### Run updateGroupsMapping
2022-10-20 02:07:05,139  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 02:07:05,140  Resetting dropped connection: api.telegram.org
2022-10-20 02:07:05,309  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 02:07:05,310  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666219024.796313}}
2022-10-20 02:07:05,311  ### Processing group: -1001683374540
2022-10-20 02:07:05,311  Time interval passed. Sending message
2022-10-20 02:07:05,312  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 02:07:05,313  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 02:07:05,573  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 811
2022-10-20 02:07:05,574  Message successfully sent.
2022-10-20 02:07:05,574  Sleeping 1800 seconds.
2022-10-20 02:37:05,628  ##################### New run
2022-10-20 02:37:05,631  ##### Run updateGroupsMapping
2022-10-20 02:37:05,633  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 02:37:05,634  Resetting dropped connection: api.telegram.org
2022-10-20 02:37:05,809  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 02:37:05,810  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666220825.31148}}
2022-10-20 02:37:05,810  ### Processing group: -1001683374540
2022-10-20 02:37:05,810  Time interval passed. Sending message
2022-10-20 02:37:05,812  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 02:37:05,812  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 02:37:06,073  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 811
2022-10-20 02:37:06,074  Message successfully sent.
2022-10-20 02:37:06,074  Sleeping 1800 seconds.
2022-10-20 03:07:06,164  ##################### New run
2022-10-20 03:07:06,166  ##### Run updateGroupsMapping
2022-10-20 03:07:06,168  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 03:07:06,169  Resetting dropped connection: api.telegram.org
2022-10-20 03:07:06,332  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 03:07:06,334  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666222625.810837}}
2022-10-20 03:07:06,334  ### Processing group: -1001683374540
2022-10-20 03:07:06,334  Time interval passed. Sending message
2022-10-20 03:07:06,336  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 03:07:06,337  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 03:07:06,572  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 811
2022-10-20 03:07:06,573  Message successfully sent.
2022-10-20 03:07:06,573  Sleeping 1800 seconds.
2022-10-20 03:37:06,624  ##################### New run
2022-10-20 03:37:06,626  ##### Run updateGroupsMapping
2022-10-20 03:37:06,629  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 03:37:06,630  Resetting dropped connection: api.telegram.org
2022-10-20 03:37:06,792  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 03:37:06,793  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666224426.3348396}}
2022-10-20 03:37:06,793  ### Processing group: -1001683374540
2022-10-20 03:37:06,794  Time interval passed. Sending message
2022-10-20 03:37:06,795  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 03:37:06,795  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 03:37:07,034  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 811
2022-10-20 03:37:07,035  Message successfully sent.
2022-10-20 03:37:07,035  Sleeping 1800 seconds.
2022-10-20 04:07:07,136  ##################### New run
2022-10-20 04:07:07,139  ##### Run updateGroupsMapping
2022-10-20 04:07:07,142  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 04:07:07,142  Resetting dropped connection: api.telegram.org
2022-10-20 04:07:07,310  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 04:07:07,312  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666226226.7940655}}
2022-10-20 04:07:07,312  ### Processing group: -1001683374540
2022-10-20 04:07:07,312  Time interval passed. Sending message
2022-10-20 04:07:07,314  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 04:07:07,314  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 04:07:07,559  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 811
2022-10-20 04:07:07,560  Message successfully sent.
2022-10-20 04:07:07,560  Sleeping 1800 seconds.
2022-10-20 04:37:07,655  ##################### New run
2022-10-20 04:37:07,657  ##### Run updateGroupsMapping
2022-10-20 04:37:07,661  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 04:37:07,662  Resetting dropped connection: api.telegram.org
2022-10-20 04:37:07,830  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 04:37:07,831  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666228027.3124864}}
2022-10-20 04:37:07,831  ### Processing group: -1001683374540
2022-10-20 04:37:07,831  Time interval passed. Sending message
2022-10-20 04:37:07,833  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 04:37:07,833  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 04:37:08,120  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 811
2022-10-20 04:37:08,121  Message successfully sent.
2022-10-20 04:37:08,122  Sleeping 1800 seconds.
2022-10-20 05:07:08,223  ##################### New run
2022-10-20 05:07:08,225  ##### Run updateGroupsMapping
2022-10-20 05:07:08,229  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 05:07:08,230  Resetting dropped connection: api.telegram.org
2022-10-20 05:07:08,390  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 05:07:08,391  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666229827.8319602}}
2022-10-20 05:07:08,391  ### Processing group: -1001683374540
2022-10-20 05:07:08,391  Time interval passed. Sending message
2022-10-20 05:07:08,393  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 05:07:08,393  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 05:07:08,654  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 811
2022-10-20 05:07:08,662  Message successfully sent.
2022-10-20 05:07:08,676  Sleeping 1800 seconds.
2022-10-20 05:37:08,709  ##################### New run
2022-10-20 05:37:08,723  ##### Run updateGroupsMapping
2022-10-20 05:37:08,730  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 05:37:08,731  Resetting dropped connection: api.telegram.org
2022-10-20 05:37:08,897  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 05:37:08,898  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666231628.391534}}
2022-10-20 05:37:08,899  ### Processing group: -1001683374540
2022-10-20 05:37:08,899  Time interval passed. Sending message
2022-10-20 05:37:08,901  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 05:37:08,902  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 05:37:09,163  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 811
2022-10-20 05:37:09,164  Message successfully sent.
2022-10-20 05:37:09,164  Sleeping 1800 seconds.
2022-10-20 06:07:09,195  ##################### New run
2022-10-20 06:07:09,197  ##### Run updateGroupsMapping
2022-10-20 06:07:09,199  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 06:07:09,200  Resetting dropped connection: api.telegram.org
2022-10-20 06:07:09,362  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 06:07:09,363  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666233428.8993213}}
2022-10-20 06:07:09,363  ### Processing group: -1001683374540
2022-10-20 06:07:09,363  Time interval passed. Sending message
2022-10-20 06:07:09,365  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 06:07:09,365  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 06:07:09,641  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 811
2022-10-20 06:07:09,642  Message successfully sent.
2022-10-20 06:07:09,642  Sleeping 1800 seconds.
2022-10-20 06:37:09,684  ##################### New run
2022-10-20 06:37:09,686  ##### Run updateGroupsMapping
2022-10-20 06:37:09,688  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 06:37:09,689  Resetting dropped connection: api.telegram.org
2022-10-20 06:37:09,864  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 06:37:09,866  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666235229.3638496}}
2022-10-20 06:37:09,866  ### Processing group: -1001683374540
2022-10-20 06:37:09,866  Time interval passed. Sending message
2022-10-20 06:37:09,868  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 06:37:09,868  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 06:37:10,164  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 811
2022-10-20 06:37:10,165  Message successfully sent.
2022-10-20 06:37:10,165  Sleeping 1800 seconds.
2022-10-20 07:07:10,264  ##################### New run
2022-10-20 07:07:10,267  ##### Run updateGroupsMapping
2022-10-20 07:07:10,270  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 07:07:10,271  Resetting dropped connection: api.telegram.org
2022-10-20 07:07:10,433  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 07:07:10,434  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666237029.8667893}}
2022-10-20 07:07:10,435  ### Processing group: -1001683374540
2022-10-20 07:07:10,435  Time interval passed. Sending message
2022-10-20 07:07:10,436  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 07:07:10,436  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 07:07:10,708  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 811
2022-10-20 07:07:10,709  Message successfully sent.
2022-10-20 07:07:10,709  Sleeping 1800 seconds.
2022-10-20 07:37:10,768  ##################### New run
2022-10-20 07:37:10,770  ##### Run updateGroupsMapping
2022-10-20 07:37:10,774  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 07:37:10,774  Resetting dropped connection: api.telegram.org
2022-10-20 07:37:10,951  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 07:37:10,953  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666238830.4351954}}
2022-10-20 07:37:10,953  ### Processing group: -1001683374540
2022-10-20 07:37:10,953  Time interval passed. Sending message
2022-10-20 07:37:10,955  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 07:37:10,956  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 07:37:11,223  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 815
2022-10-20 07:37:11,225  Message successfully sent.
2022-10-20 07:37:11,225  Sleeping 1800 seconds.
2022-10-20 08:07:11,326  ##################### New run
2022-10-20 08:07:11,330  ##### Run updateGroupsMapping
2022-10-20 08:07:11,334  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 08:07:11,335  Resetting dropped connection: api.telegram.org
2022-10-20 08:07:11,490  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 08:07:11,491  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666240630.9535012}}
2022-10-20 08:07:11,492  ### Processing group: -1001683374540
2022-10-20 08:07:11,492  Time interval passed. Sending message
2022-10-20 08:07:11,493  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 08:07:11,494  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 08:07:11,762  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 811
2022-10-20 08:07:11,763  Message successfully sent.
2022-10-20 08:07:11,763  Sleeping 1800 seconds.
2022-10-20 08:37:11,852  ##################### New run
2022-10-20 08:37:11,854  ##### Run updateGroupsMapping
2022-10-20 08:37:11,857  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 08:37:11,857  Resetting dropped connection: api.telegram.org
2022-10-20 08:37:12,029  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 08:37:12,031  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666242431.4923835}}
2022-10-20 08:37:12,031  ### Processing group: -1001683374540
2022-10-20 08:37:12,031  Time interval passed. Sending message
2022-10-20 08:37:12,033  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 08:37:12,033  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 08:37:12,297  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 811
2022-10-20 08:37:12,298  Message successfully sent.
2022-10-20 08:37:12,298  Sleeping 1800 seconds.
2022-10-20 09:07:12,360  ##################### New run
2022-10-20 09:07:12,362  ##### Run updateGroupsMapping
2022-10-20 09:07:12,366  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 09:07:12,367  Resetting dropped connection: api.telegram.org
2022-10-20 09:07:12,542  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 09:07:12,543  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666244232.0318756}}
2022-10-20 09:07:12,543  ### Processing group: -1001683374540
2022-10-20 09:07:12,544  Time interval passed. Sending message
2022-10-20 09:07:12,545  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 09:07:12,545  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 09:07:12,815  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 811
2022-10-20 09:07:12,817  Message successfully sent.
2022-10-20 09:07:12,817  Sleeping 1800 seconds.
2022-10-20 09:37:12,860  ##################### New run
2022-10-20 09:37:12,862  ##### Run updateGroupsMapping
2022-10-20 09:37:12,864  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 09:37:12,865  Resetting dropped connection: api.telegram.org
2022-10-20 09:37:13,027  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 09:37:13,028  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666246032.5440192}}
2022-10-20 09:37:13,029  ### Processing group: -1001683374540
2022-10-20 09:37:13,029  Time interval passed. Sending message
2022-10-20 09:37:13,030  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 09:37:13,030  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 09:37:13,348  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 811
2022-10-20 09:37:13,349  Message successfully sent.
2022-10-20 09:37:13,350  Sleeping 1800 seconds.
2022-10-20 10:07:13,436  ##################### New run
2022-10-20 10:07:13,439  ##### Run updateGroupsMapping
2022-10-20 10:07:13,443  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 10:07:13,444  Resetting dropped connection: api.telegram.org
2022-10-20 10:07:13,610  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 10:07:13,612  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666247833.0292194}}
2022-10-20 10:07:13,612  ### Processing group: -1001683374540
2022-10-20 10:07:13,613  Time interval passed. Sending message
2022-10-20 10:07:13,620  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 10:07:13,620  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 10:07:13,898  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 811
2022-10-20 10:07:13,899  Message successfully sent.
2022-10-20 10:07:13,899  Sleeping 1800 seconds.
2022-10-20 10:37:13,988  ##################### New run
2022-10-20 10:37:13,992  ##### Run updateGroupsMapping
2022-10-20 10:37:13,998  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 10:37:13,999  Resetting dropped connection: api.telegram.org
2022-10-20 10:37:14,177  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 10:37:14,178  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666249633.6130211}}
2022-10-20 10:37:14,179  ### Processing group: -1001683374540
2022-10-20 10:37:14,179  Time interval passed. Sending message
2022-10-20 10:37:14,181  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 10:37:14,181  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 10:37:14,442  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 811
2022-10-20 10:37:14,443  Message successfully sent.
2022-10-20 10:37:14,446  Sleeping 1800 seconds.
2022-10-20 11:07:14,506  ##################### New run
2022-10-20 11:07:14,509  ##### Run updateGroupsMapping
2022-10-20 11:07:14,512  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 11:07:14,513  Resetting dropped connection: api.telegram.org
2022-10-20 11:07:14,676  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 11:07:14,677  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666251434.179373}}
2022-10-20 11:07:14,677  ### Processing group: -1001683374540
2022-10-20 11:07:14,677  Time interval passed. Sending message
2022-10-20 11:07:14,679  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 11:07:14,680  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 11:07:14,975  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 811
2022-10-20 11:07:14,977  Message successfully sent.
2022-10-20 11:07:14,977  Sleeping 1800 seconds.
2022-10-20 11:16:23,426  Quit
